---
name: Bug Report
about: Found a bug? Report the bug here!
title: "[BUG]: "
labels:
  - bug
url: https://example.com/bug-report-template

---
name: Feedback
about: Got anything that I could improve on or just tell me how much you love FontFlex
title: "[USER-FEEDBACK]: "
labels:
  - user-feedback
url: https://example.com/feedback-template

---
name: Feature Request
about: Something on your mind that would be nice to have on 1Habit
title: "[FEATURE-REQUEST]: "
labels:
  - feature-request
url: https://github.com/jasjs1/1Habit/blob/main/.github/ISSUE_TEMPLATE/FeatureRequest.md